apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  TMDB_API_KEY: {{ .Values.tmdb.apiKey | b64enc | quote }}