apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  TMDB-API-READ-ACCESS-TOKEN: {{ .Values.tmdb.apiKey | b64enc | quote }}