{{ if and (index .Values "modules" "text2vec-cohere" "enabled") (index .Values "modules" "text2vec-cohere" "apiKey") }}
apiVersion: v1
kind: Secret
metadata:
  name: weaviate-cohere
type: Opaque
data:
  apiKey: {{ index .Values "modules" "text2vec-cohere" "apiKey" | b64enc }}
{{ end }}
