{{-  $t2vOpenAI := and (index .Values "modules" "text2vec-openai" "enabled") (index .Values "modules" "text2vec-openai" "apiKey") -}}
{{-  $qnaOpenAI := and (index .Values "modules" "qna-openai" "enabled") (index .Values "modules" "qna-openai" "apiKey") }}
{{-  $openAI := or ($t2vOpenAI) ($qnaOpenAI) }}
{{ if $openAI }}

{{ if and (index .Values "modules" "text2vec-openai" "apiKey") (index .Values "modules" "qna-openai" "apiKey") }}
  {{ if ne (index .Values "modules" "text2vec-openai" "apiKey") (index .Values "modules" "qna-openai" "apiKey") }}
    {{- fail "Two OpenAI modules activated, but their keys differ. Use the same key on all activated OpenAI modules." }}
  {{ end }}
{{ end }}

apiVersion: v1
kind: Secret
metadata:
  name: weaviate-openai
type: Opaque
data:
  {{- if (index .Values "modules" "qna-openai" "apiKey") }}
  apiKey: {{ index .Values "modules" "qna-openai" "apiKey" | b64enc }}
  {{- else }}
  apiKey: {{ index .Values "modules" "text2vec-openai" "apiKey" | b64enc }}
  {{- end }}
{{ end }}
