name: Movie Recommender Build

on:
  push:
    branches: [ main, feature/add-pipelines ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: build & push
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:MovieRecommender/backend"
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/movie-recommender:${{ github.sha }},ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/movie-recommender:latest


  deploy:
    name: deploy to k8s
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3

    - name: Helm Deploy to k8s
      uses: vimeda/helm@v1.6.8
      with:
        release: 'movie-recommender'
        namespace: 'vector-search'
        chart: 'helm/MovieRecommender/backend'
        token: '${{ secrets.GITHUB_TOKEN }}'
        values: |
          image:
            tag: ${{ github.sha }}
          tmdb:
            apiKey: ${{ secrets.TMDB_API_KEY }}
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'