name: ImageSearchCoreService Build

on:
  push:
    branches: [ main, feature/add-pipelines ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: build & push
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ImageSearchCoreService

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: assemble
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assemble

    - name: check
      uses: gradle/gradle-build-action@v2
      with:
        arguments: check

    - name: build container
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build -x test -Dquarkus.container-image.build=true

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: true

    - name: Push Container
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build -x test -Dquarkus.container-image.push=true -Dquarkus.container-image.group=${{ github.repository_owner }} -Dquarkus.container-image.name=${{ github.event.repository.name }}/image-search-core-service -Dquarkus.container-image.registry=ghcr.io -Dquarkus.container-image.additional-tags=${{ github.sha }},latest
